GUIDES = [
 {
  "id": "guide-how-to-write-a-consulting-cv-for-mbb-and-tier-2-firms",
  "cat": "consulting",
  "title": "How to write a consulting CV for MBB and Tier 2 firms",
  "mins": "6 min read",
  "body": "<p>Most consulting CVs read as a list of duties. The ones that get interviews read as a list of results: what changed because you were there. A screener at a strategy firm is usually spending well under a minute on your CV, and they are asking one question — is there enough evidence here to justify thirty minutes in a room?</p>\n<h4>What screeners look for</h4>\n<ul><li><strong>Impact</strong> — measurable outcomes, not responsibilities.</li><li><strong>Problem-solving</strong> — evidence you have worked through ambiguous, analytical problems.</li><li><strong>Leadership</strong> — moments where you moved people, not just tasks.</li><li><strong>Academic and professional signal</strong> — grades, test scores, awards and employers, stated plainly.</li></ul>\n<h4>Write every bullet the same way</h4>\n<p>Lead with the outcome, then show how you got there. “Reduced onboarding time by 30% by redesigning the handover process across three teams” beats “Responsible for onboarding process improvement.” For every line, ask “so what?” — if the answer is nothing measurable, either quantify it or cut it.</p>\n<h4>Format rules that matter</h4>\n<ul><li>One page for anyone under roughly ten years of experience.</li><li>Clean, conventional layout — no photos, graphics, skill bars or columns that break when a recruiter’s system parses them.</li><li>Education at the top if you are a student or recent graduate; experience first once you have a few years behind you.</li><li>A short “additional” section for languages, notable achievements and genuine interests — Arabic and other languages are real assets for Middle East offices, so list them with your level.</li></ul>\n<h4>MBB vs Tier 2</h4>\n<p>The CV standard is essentially the same. What changes is your target list and how much the CV has to carry: at the most selective firms, a referral and a very clean CV together get you into the process; at Tier 2 and boutique firms, relevant sector or functional experience can weigh more heavily, so make it visible near the top.</p>\n<p class=\"guide-cta\">Want a line-by-line read of yours? <a href=\"{{cv-review}}\">Mada CV Review</a> or <a href=\"{{services#cv-linkedin}}\">a live CV &amp; LinkedIn session</a>.</p>"
 },
 {
  "id": "guide-consulting-case-interview-preparation-plan",
  "cat": "consulting",
  "title": "Consulting case interview preparation plan",
  "mins": "7 min read",
  "body": "<p>Case interviews reward structured thinking under pressure, and that is a skill built through repetition, not reading. The mistake most candidates make is spending weeks on books and frameworks and very little time actually solving cases out loud with feedback.</p>\n<h4>Phase 1 — Foundations (first 1–2 weeks)</h4>\n<ul><li>Learn how a case unfolds: clarifying the objective, building a structure, analyzing data, and landing a recommendation.</li><li>Practise mental math daily — percentages, growth rates, large-number multiplication — until it stops being a source of stress.</li><li>Read a handful of solved cases to see what a good answer sounds like, then stop reading.</li></ul>\n<h4>Phase 2 — Volume with a partner (next 3–4 weeks)</h4>\n<ul><li>Aim for regular live cases, alternating between being the candidate and the interviewer — giving cases teaches you what interviewers are listening for.</li><li>Build your own structures for each case rather than reusing a memorized framework. Interviewers notice the difference immediately.</li><li>Keep a log of recurring mistakes and work on one at a time.</li></ul>\n<h4>Phase 3 — Pressure-testing (final 1–2 weeks)</h4>\n<ul><li>Do full mock interviews with people who have interviewed for real, in the format your target firm uses (interviewer-led or candidate-led).</li><li>Practise the synthesis: a crisp, top-down recommendation with next steps, delivered in under a minute.</li><li>Prepare your fit stories in parallel — many candidates lose offers on fit after passing the case.</li></ul>\n<h4>How you know you are ready</h4>\n<p>You can structure an unfamiliar problem in a couple of minutes, handle a data exhibit without freezing, do the math out loud without losing the thread, and finish with a clear answer. If one of those still breaks under pressure, that is where your remaining time should go.</p>\n<p class=\"guide-cta\">Want a realistic mock with feedback? See <a href=\"{{services#mock}}\">Mock interviews</a>.</p>"
 },
 {
  "id": "guide-fit-interview-questions-and-how-to-structure-answers",
  "cat": "consulting",
  "title": "Fit interview questions and how to structure answers",
  "mins": "5 min read",
  "body": "<p>Fit interviews are not the soft part of the process. Firms use them to decide whether they would put you in front of a client and whether a team would want to work with you at 11pm. A strong case with a weak fit round rarely becomes an offer.</p>\n<h4>The questions you will almost certainly get</h4>\n<ul><li>Walk me through your CV / tell me about yourself.</li><li>Why consulting? Why this firm?</li><li>Tell me about a time you led a team or influenced without authority.</li><li>Tell me about a time you faced a significant challenge or failure.</li><li>Tell me about an achievement you are proud of.</li></ul>\n<h4>A structure that works</h4>\n<p>Use a simple story arc — situation, what you specifically did, the result, and what you learned. Spend most of the time on your actions, and keep the setup short. A good answer is usually two to three minutes, told with enough detail that the interviewer can picture it.</p>\n<h4>“Why consulting” and “why this firm”</h4>\n<p>Generic answers (“steep learning curve, variety of industries”) are true for everyone and therefore say nothing about you. Anchor your answer in your own experience — a moment where you enjoyed the kind of work consultants do — and support “why this firm” with specifics from people you have spoken to there.</p>\n<h4>Prepare for the follow-ups</h4>\n<p>Experienced interviewers dig: “What would you do differently?” “What did your manager think?” “What was your specific contribution?” If your story only survives the first telling, it is not ready.</p>\n<p class=\"guide-cta\">Build your stories once and reuse them across every fit round — see <a href=\"{{resources#guide-how-to-build-a-star-story-bank}}\">How to build a STAR story bank</a>.</p>"
 },
 {
  "id": "guide-how-to-build-a-star-story-bank",
  "cat": "consulting",
  "title": "How to build a STAR story bank",
  "mins": "5 min read",
  "body": "<p>A story bank is a set of prepared examples from your experience that you can adapt to almost any behavioral question. It is the single most useful piece of preparation for consulting fit rounds.</p>\n<h4>Step 1 — List your raw material</h4>\n<p>Write down 12–15 moments from your work, studies and life: projects, launches, conflicts, failures, times you led, times you changed someone’s mind, times you delivered under pressure.</p>\n<h4>Step 2 — Write each one in STAR</h4>\n<ul><li><strong>Situation</strong> — the context, in two sentences.</li><li><strong>Task</strong> — what you were responsible for.</li><li><strong>Action</strong> — what you specifically did. This should be most of the story.</li><li><strong>Result</strong> — the outcome, quantified wherever possible, and what you learned.</li></ul>\n<h4>Step 3 — Map stories to themes</h4>\n<p>Build a simple grid: stories down one side, themes (leadership, ownership, conflict, failure, customer focus, analytical thinking, delivering results) across the top. Mark which stories can answer which themes. Aim for at least two strong stories per theme, so you never have to repeat yourself across a full interview day.</p>\n<h4>Step 4 — Stress-test them</h4>\n<p>Tell each story out loud, then have someone ask “why?”, “what would you do differently?” and “what was your specific role?” If the story holds up, keep it. If it falls apart, replace it.</p>\n<p class=\"guide-cta\">Want your stories pressure-tested by someone who has interviewed? See <a href=\"{{services#mock}}\">Mock interviews</a>.</p>"
 },
 {
  "id": "guide-experienced-hire-consulting-recruiting-in-the-gcc",
  "cat": "consulting",
  "title": "Experienced-hire consulting recruiting in the Middle East",
  "mins": "6 min read",
  "body": "<p>Experienced-hire recruiting runs very differently from graduate recruiting. There is usually no fixed annual cycle and no on-campus process — firms hire when they need people, often for specific practices or client work. That makes it more flexible, and much more dependent on how well you are positioned and connected.</p>\n<h4>How the process usually works</h4>\n<ul><li>Roles are filled through referrals, direct applications, and specialist headhunters, often in parallel.</li><li>Firms typically hire into a practice or sector, so your target should be specific: a firm <em>and</em> a practice where your background is directly relevant.</li><li>Interviews still include cases, but expect more questions about your sector knowledge and how you would add value on day one.</li></ul>\n<h4>Positioning your experience</h4>\n<p>The question behind every experienced-hire interview is “what do you bring that we can’t easily train?” Translate your experience into consulting language: problems solved, stakeholders managed, decisions influenced, and measurable impact. Sector depth — energy, government, financial services, healthcare and others — is often your strongest card.</p>\n<h4>Level matters as much as the offer</h4>\n<p>Entry level is one of the most consequential and most negotiable outcomes of experienced-hire recruiting. Understand how your years of experience and seniority map to the firm’s levels before you interview, not after you receive an offer.</p>\n<h4>Middle East-specific considerations</h4>\n<ul><li>Regional experience and relationships are valued; say clearly where you have worked and with whom.</li><li>Arabic language ability can matter for public-sector-heavy practices — state your level honestly.</li><li>Nationalization priorities in some markets can affect which roles are open to which candidates; ask early rather than assume.</li></ul>\n<p class=\"guide-cta\">Not sure which practice or level to target? Start with <a href=\"{{services#career-strategy}}\">Career strategy</a>.</p>"
 },
 {
  "id": "guide-how-consulting-recruiting-works-in-saudi-arabia",
  "cat": "gcc",
  "title": "How consulting recruiting works in Saudi Arabia",
  "mins": "6 min read",
  "body": "<p>Saudi Arabia has become one of the most active consulting markets in the region, with large transformation programmes across government and the private sector creating sustained demand for consultants. For candidates, that means real opportunity — and a recruiting process with its own specifics.</p>\n<h4>Who is hiring</h4>\n<p>Strategy firms, Big Four and advisory firms, and boutique consultancies all have a presence in Riyadh, and many work heavily with public-sector clients. Increasingly, candidates also move between consulting and in-house strategy roles at large Saudi organizations.</p>\n<h4>How candidates enter</h4>\n<ul><li><strong>Graduates</strong> — through university recruiting, internships and scholarship-linked pathways, as well as direct applications.</li><li><strong>Experienced hires</strong> — through referrals, direct applications and headhunters, often for specific practices.</li><li><strong>Returning Saudis</strong> — students abroad frequently recruit into Saudi offices through international campus events and networks.</li></ul>\n<h4>What is different</h4>\n<ul><li>Nationalization priorities mean some roles are specifically aimed at Saudi nationals; others are open more broadly. Understand which applies before you invest time.</li><li>Arabic fluency is often an advantage, particularly for public-sector work.</li><li>Interview formats follow each firm’s global standard — cases and fit — so preparation quality matters as much as in any other office.</li></ul>\n<h4>What to do next</h4>\n<p>Build a realistic target list across firm tiers, identify two or three people at each firm to speak to, and start case preparation earlier than you think you need to.</p>\n<p class=\"guide-cta\">Map your target list with <a href=\"{{services#career-strategy}}\">Career strategy</a>, or read <a href=\"{{resources#guide-dubai-vs-riyadh-consulting-recruiting}}\">Dubai vs Riyadh consulting recruiting</a>.</p>"
 },
 {
  "id": "guide-dubai-vs-riyadh-consulting-recruiting",
  "cat": "gcc",
  "title": "Dubai vs Riyadh consulting recruiting",
  "mins": "5 min read",
  "body": "<p>Many candidates treat “the Middle East” as one market. In practice, Dubai and Riyadh offices often recruit differently, serve different client mixes, and suit different profiles. Choosing deliberately — or applying to both with a clear rationale — is part of a good strategy.</p>\n<h4>Dubai</h4>\n<ul><li>Often acts as a regional hub, with teams working across multiple countries in the Middle East.</li><li>A highly international talent pool, which means strong competition from candidates worldwide.</li><li>A broader mix of private-sector clients alongside government work.</li></ul>\n<h4>Riyadh</h4>\n<ul><li>Significant demand driven by large-scale transformation work, with a heavier weight of public-sector and government-related clients.</li><li>Nationalization priorities shape hiring, which can make it a particularly strong option for Saudi candidates.</li><li>Arabic ability and local context are frequently valued in client-facing work.</li></ul>\n<h4>How to choose</h4>\n<p>Ask three questions: Where is my network strongest? Which client work genuinely interests me? Where does my profile — nationality, languages, sector experience — give me a natural advantage? Then speak to consultants in each office; the differences in day-to-day work are best heard first-hand.</p>\n<h4>Applying to both</h4>\n<p>Some firms let you state an office preference or apply to more than one; others route you through a single process. Check each firm’s rules, and make sure your “why this office” answer is specific and consistent with your application.</p>\n<p class=\"guide-cta\">Unsure which office fits? Talk it through on a <a href=\"{{book}}\">free intro call</a>.</p>"
 },
 {
  "id": "guide-networking-for-gcc-consulting-roles",
  "cat": "gcc",
  "title": "Networking for Middle East consulting roles",
  "mins": "5 min read",
  "body": "<p>In Middle East consulting recruiting, relationships carry real weight. A thoughtful conversation with the right person can shape whether your application is noticed. But networking only works when it doesn’t feel transactional — to them or to you.</p>\n<h4>Who to talk to</h4>\n<ul><li>Alumni from your university or former employers now at your target firms.</li><li>Consultants one or two levels above your entry point — close enough to remember recruiting, senior enough to be heard.</li><li>People in the specific office you are targeting, not just the firm globally.</li></ul>\n<h4>How to reach out</h4>\n<p>Lead with a specific question you couldn’t answer by searching, not a request for a referral. Keep the first message short: who you are, why them specifically, and a request for a brief conversation. People respond to curiosity about their actual experience, not to being used as a means to an application.</p>\n<h4>In the conversation</h4>\n<ul><li>Prepare three or four real questions about their work, their office and what they wish they had known.</li><li>Have a crisp one-minute version of your own story ready.</li><li>Ask, near the end, whether there is anyone else they think you should speak to.</li></ul>\n<h4>After</h4>\n<p>Thank them the same day. Follow up once with something useful — an update on your application, or something relevant they mentioned — and let the relationship, not the ask, decide what happens next. If a referral comes, it will be because they are confident in you.</p>\n<p class=\"guide-cta\">Want a structured outreach plan and templates? See <a href=\"{{services#apply-network}}\">Application &amp; networking strategy</a>.</p>"
 },
 {
  "id": "guide-how-to-return-to-the-gcc-after-studying-abroad",
  "cat": "gcc",
  "title": "How to return to the Middle East after studying abroad",
  "mins": "5 min read",
  "body": "<p>Studying abroad gives you a strong profile — and a practical problem. You are recruiting for a market you are not physically in, often on a different timeline from the one your university runs on.</p>\n<h4>Start earlier than your classmates</h4>\n<p>Middle East recruiting timelines don’t always match your university’s campus cycle. Find out when your target firms’ regional offices recruit, and work backwards from there.</p>\n<h4>Use the channels built for you</h4>\n<ul><li>International recruiting events and firm presentations aimed at Middle East students abroad.</li><li>Scholarship and sponsorship networks, where relevant.</li><li>Alumni from your university already working in Middle East offices — often the most responsive contacts you have.</li></ul>\n<h4>Make the case for coming back</h4>\n<p>Interviewers want to know you genuinely intend to build your career in the region. Your “why this office” answer should be specific: family, long-term plans, the kind of work happening locally, and what you bring from your time abroad.</p>\n<h4>Handle the logistics</h4>\n<ul><li>Interviews may be virtual or require travel — ask early and plan around exams.</li><li>Be clear on your graduation date, availability and any visa or sponsorship questions relevant to your nationality.</li><li>Keep your CV in a format that works for regional recruiters: clean, one page, with languages listed.</li></ul>\n<p class=\"guide-cta\">Recruiting from abroad? Start with <a href=\"{{services#career-strategy}}\">Career strategy</a> to map realistic targets.</p>"
 },
 {
  "id": "guide-should-you-move-from-big-four-to-strategy-consulting",
  "cat": "career",
  "title": "Should you move from Big Four to strategy consulting?",
  "mins": "5 min read",
  "body": "<p>It is one of the most common moves we coach, and one of the most misunderstood. Big Four and advisory experience is valuable, but strategy firms test for something specific, and the transition works best when you understand the gap before you apply.</p>\n<h4>Reasons it can be the right move</h4>\n<ul><li>You want to work on top-management questions — growth, portfolio, operating model — rather than implementation or technical advisory.</li><li>You enjoy structured problem-solving and want more of it.</li><li>You are open to the pace and ambiguity that comes with it.</li></ul>\n<h4>Reasons to pause</h4>\n<ul><li>You are mainly motivated by title or pay — the day-to-day is different enough that this rarely sustains you.</li><li>You would need to re-enter at a lower level and haven’t thought through whether that trade-off is worth it.</li><li>Your strongest path might actually be a strategy role within your current firm or an in-house strategy team.</li></ul>\n<h4>The real gap</h4>\n<p>For most advisory candidates, the gap is not experience — it is case method. Strategy interviews reward top-down structuring, hypothesis-driven thinking and clear synthesis, which is different from how many advisory projects are run. Your CV needs reframing too: from deliverables and workstreams to problems solved and decisions influenced.</p>\n<h4>How to decide</h4>\n<p>Speak to two or three people who made the move, be honest about why you want it, and understand the level you would realistically enter at. Then decide.</p>\n<p class=\"guide-cta\">Weighing the move? Start with <a href=\"{{services#career-strategy}}\">Career strategy</a>.</p>"
 },
 {
  "id": "guide-your-first-90-days-in-consulting",
  "cat": "career",
  "title": "Your first 90 days in consulting",
  "mins": "5 min read",
  "body": "<p>First impressions in consulting are formed fast, and they follow you from project to project. The first 90 days are less about brilliance than about becoming someone a manager can rely on.</p>\n<h4>Days 1–30: learn how the team works</h4>\n<ul><li>Understand what your manager expects: how they want updates, how often, and in what format.</li><li>Master the basics — firm templates, slide standards, the tools the team uses.</li><li>Ask good questions early, and write down the answers so you don’t ask twice.</li></ul>\n<h4>Days 31–60: own something</h4>\n<ul><li>Take full ownership of a piece of analysis or a workstream, however small.</li><li>Check your work before you send it — accuracy builds trust faster than speed.</li><li>Ask for feedback directly, and act on it visibly.</li></ul>\n<h4>Days 61–90: build your reputation</h4>\n<ul><li>Start anticipating what your manager will need next, not just what they asked for.</li><li>Build relationships beyond your project — with peers, other managers and your staffing team.</li><li>Think about what you want your next project to be, and let the right people know.</li></ul>\n<h4>What gets people into trouble</h4>\n<p>Surprises. Missing a deadline is survivable; missing it without warning is not. Flag risks early and bring a proposed solution when you do.</p>\n<p class=\"guide-cta\">Want a sounding board for your first months? See <a href=\"{{services#progress}}\">Progress</a>.</p>"
 },
 {
  "id": "guide-how-to-negotiate-a-gcc-offer",
  "cat": "career",
  "title": "How to negotiate a Middle East offer",
  "mins": "6 min read",
  "body": "<p>Middle East offers are structured differently from many other markets, and candidates who evaluate them only on headline salary often miss what actually matters. Before you negotiate, understand what you have been offered.</p>\n<h4>Know the structure</h4>\n<ul><li><strong>Basic salary</strong> — often only part of the monthly package, and frequently the figure end-of-service benefits are calculated on.</li><li><strong>Allowances</strong> — housing and transport are common; some packages also include education or other allowances.</li><li><strong>End-of-service gratuity</strong> — a payment on leaving, typically linked to basic salary and years of service. A package weighted heavily towards allowances can mean a smaller gratuity.</li><li><strong>Other terms</strong> — annual flights, medical cover for dependants, relocation support, bonus structure, notice period and probation.</li></ul>\n<h4>Three questions to answer before you negotiate</h4>\n<p>First: what does this offer look like against the market for this role, level and location — not against your last salary? Second: what matters more to you right now, cash or the things around it (title, scope, start date, relocation support)? Third: what’s your actual walk-away point, decided before the call, not during it? Negotiating without answers to these three is negotiating on the other side’s terms.</p>\n<h4>How to negotiate</h4>\n<ul><li>Express genuine enthusiasm for the role first.</li><li>Make one clear, reasoned request rather than a list of small ones.</li><li>Anchor on market data and your specific value, not personal need.</li><li>If base salary is fixed, ask about level, sign-on, allowances, start date or review timing.</li></ul>\n<p>Get the final terms in writing, and read the contract carefully before you sign.</p>\n<p class=\"guide-cta\">Holding an offer? <a href=\"{{services#offer}}\">Offer evaluation &amp; negotiation</a> covers review, benchmarking and a rehearsal of the conversation.</p>"
 }
]
